import streamlit as st
import pandas as pd
import numpy as np
import joblib
import plotly.express as px
import os
from fpdf import FPDF
from datetime import datetime


# =========================
# Login Page
# =========================

def login(username,password):

    users = pd.read_csv("data/users.csv")

    st.write(users.columns.tolist())
    st.write(users)

    return True
# ==========================
# Save Prediction to CSV
# ==========================

def save_prediction(disease,risk,age,gender):

    file_path = "data/prediction_history.csv"
 
    row = pd.DataFrame([{
        "Disease": disease,
        "Risk": risk,
        "Age": age,
        "Gender": gender
    }])

    if not os.path.exists(file_path):

        row.to_csv(
            file_path,
            index=False
        )

    else:

        row.to_csv(
            file_path,
            mode="a",
            header=False,
            index=False
        )

# ==========================
# PDF Report Download
# ==========================

def create_pdf(
    patient_name,
    age,
    gender,
    disease,
    risk_level,
    recommendations=[]
):

    pdf = FPDF()
    pdf.add_page()
    # Title
    pdf.set_font("Arial", "B", 18)
    pdf.cell(200,10,"Healthcare Prediction Report",ln=True,align="C")

    pdf.ln(10)

    # Date
    pdf.set_font("Arial", "", 11)

    pdf.cell(200,10,f"Generated On: {datetime.now().strftime('%d-%m-%Y %H:%M')}",ln=True)

    pdf.ln(5)

    # Patient Details
    pdf.set_font("Arial", "B", 14)
    pdf.cell(200,10,"Patient Information",ln=True)

    pdf.set_font("Arial","",12)

    pdf.cell(200,8,f"Name: {patient_name}",ln=True)
    pdf.cell(200,8,f"Age: {age}",ln=True)
    pdf.cell(200,8,f"Gender: {gender}",ln=True)

    pdf.ln(5)

    # Prediction
    pdf.set_font("Arial","B",14)
    pdf.cell(200,10,"Prediction Results",ln=True)

    pdf.set_font("Arial","",12)

    pdf.cell(200,8,f"Predicted Disease: {disease}",ln=True)

    pdf.cell(200,8,f"Risk Level: {risk_level}",ln=True)

    pdf.ln(5)

    # Recommendations
    pdf.set_font("Arial","B",14)
    pdf.cell(200,10,"Recommendations",ln=True)

    pdf.set_font("Arial","",12)

    for rec in recommendations:
        pdf.cell(200,8,f"- {rec}",ln=True)

    pdf.ln(10)
    pdf.set_font("Arial","I",10)

    pdf.multi_cell(0,6,
        "Disclaimer: This report is generated by an AI Healthcare Recommendation System and should not replace professional medical advice."
    )
    file_name = "Health_Report.pdf"
    pdf.output(file_name)
    return file_name

# ==========================
# PAGE CONFIG
# ==========================

st.set_page_config(
    page_title="Healthcare Recommendation System",
    page_icon="🏥",
    layout="wide"
)
st.markdown("""
<style>
.stApp{
    background: linear-gradient(to right,#e0f7fa,#f8fbff);
}
[data-testid="metric-container"]{
    background:white;
    border-radius:15px;
    padding:20px;
    box-shadow:0px 4px 15px rgba(0,0,0,0.15);
}
section[data-testid="stSidebar"]{
    background:linear-gradient(180deg,#0f172a,#1e3a8a);
}
section[data-testid="stSidebar"] *{
    color:white !important;
}
.stButton>button{
    background:linear-gradient(90deg,#2563eb,#06b6d4);
    color:white;
    border:none;
    border-radius:10px;
    font-weight:bold;
}
</style>""", unsafe_allow_html=True)

# ==========================
# LOAD DATA
# ==========================

@st.cache_data
def load_data():
    return pd.read_csv("data/Cleaned_Dataset.csv")

df = load_data()

# ==========================
# LOAD MODEL
# ==========================

model = joblib.load("models/disease_model.pkl")
risk_model = joblib.load("models/risk_model.pkl")
encoders = joblib.load("models/encoders.pkl")
st.sidebar.success("Models Loaded")

# ==========================
# SIDEBAR
# ==========================

st.sidebar.title("🏥 Healthcare System")

page = st.sidebar.radio(
    "Navigation",
    [
        "Dashboard",
        "Disease Prediction",
        "Analytics",
        "Recommendations",
        "Prediction History"
    ]
)


if "logged_in" not in st.session_state:
    st.session_state.logged_in = False

if not st.session_state.logged_in:
    st.markdown("""
            <label style="
                color:#ff2b2b;
                font-size:26px;
                font-weight:600;
            ">
            Username
            </label>
            """, unsafe_allow_html=True)
    username = st.text_input("", key="username")
    st.markdown("""
            <label style="
                color:#2563eb;
                font-size:26px;
                font-weight:600;
            ">
            Password
            </label>
            """, unsafe_allow_html=True)
    password = st.text_input("", type="password", key="password")

    if st.button("Login"):
        if login(username,password):
            st.session_state.logged_in=True
            st.rerun()
        else:
            st.error("Invalid Credentials")
    st.stop()
    

# ==========================
# DASHBOARD
# ==========================

if page == "Dashboard":
    st.markdown("""
    <h1 style='text-align:center;color:#1e3a8a'>
    🏥 Healthcare Recommendation System
    </h1>
    <h4 style='text-align:center;color:gray'>
    AI Powered Disease & Risk Prediction Dashboard
    </h4>""", unsafe_allow_html=True)

    st.markdown("""
            <style>

            [data-testid="stMetricValue"] {
                color: #FF4B4B !important;   /* Red */
                font-size: 40px !important;
                font-weight: bold !important;
            }

            [data-testid="stMetricLabel"] {
                color: #1E3A8A !important;   /* Blue */
                font-size: 18px !important;
                font-weight: bold !important;
            }

            </style>
            """, unsafe_allow_html=True)

    col1,col2,col3,col4 = st.columns(4)

    with col1:
        st.metric("👨‍⚕️ Total Patients",len(df),delta_color='blue')

    with col2:
        st.metric("🏥 Diseases",df["disease"].nunique())

    with col3:
        st.metric("📈 Avg Age",round(df["age"].mean(),1))

    with col4:
        st.metric("⚠️ High Risk",len(df[df["risk_level"]=="High"]))

    st.divider()

    c1,c2 = st.columns(2)

    with c1:

        disease_count = (
            df["disease"]
            .value_counts()
            .reset_index()
        )

        disease_count.columns = [
            "Disease",
            "Count"
        ]

        fig = px.bar(
            disease_count,
            x="Disease",
            y="Count",
            title="Disease Distribution"
        )

        st.plotly_chart(
            fig,
            use_container_width=True
        )

    with c2:

        fig2 = px.pie(
            df,
            names="gender",
            title="Gender Distribution"
        )

        st.plotly_chart(
            fig2,
            use_container_width=True
        )

        st.markdown("---")
        st.markdown("""
            <div style="
            text-align:center;
            padding:15px;
            border-radius:15px;
            background:linear-gradient(90deg,#DBEAFE,#FEE2E2);
            ">
            <h3 style="margin:0;">
            <span style="color:#1D4ED8;">🏥 Healthcare</span>
            <span style="color:#DC2626;"> Recommendation System</span>
            </h3>
            <p style="
            margin-top:10px;
            font-size:18px;
            font-weight:bold;">
            <span style="color:#1E3A8A;">Developed By</span>
            <span style="color:#DC2626;"> Sahil Khan</span>
            </p>
            </div>""", unsafe_allow_html=True)

# ==========================
# DISEASE PREDICTION
# ==========================

elif page == "Disease Prediction":

    st.markdown("""
    <h2 style='color:#2563eb'>
    🩺 Disease & Risk Prediction
    </h2>""", unsafe_allow_html=True)

    st.markdown("""
            <style>
            label{
                color:#1E3A8A !important;
                font-weight:700 !important;
                font-size:17px !important;
            }
            .stSelectbox div[data-baseweb="select"]{
                border-radius:12px;
            }
            .stNumberInput input{
                border-radius:12px;
            }
            .stTextInput input{
                border-radius:12px;
            }
            .stButton button{
                background:linear-gradient(90deg,#2563EB,#7C3AED);
                color:white;
                border:none;
                border-radius:12px;
                height:50px;
                font-size:18px;
                font-weight:bold;
            }
            </style>""", unsafe_allow_html=True)

    col1,col2 = st.columns(2)

    with col1:
        fever = st.selectbox("Fever", ["Yes","No"])
        cough = st.selectbox("Cough",["Yes","No"])
        fatigue = st.selectbox("Fatigue",["Yes","No"])
        breathing = st.selectbox("Difficulty Breathing", ["Yes","No"])
    with col2:
        patient_name = st.text_input("Patient Name")
        age = st.number_input("Age",1,100,25)
        gender = st.selectbox("Gender",["male","female"])
        bp = st.number_input("Blood Pressure",50,250,120)
        cholesterol = st.number_input("Cholesterol",50,400,180)

    if st.button("Predict Disease"):

        fever_enc = encoders["fever"].transform([fever])[0]
        cough_enc = encoders["cough"].transform([cough])[0]
        fatigue_enc = encoders["fatigue"].transform([fatigue])[0]

        breathing_enc = encoders["difficulty_breathing"].transform([breathing])[0]

        gender_enc = encoders["gender"].transform([gender])[0]

        input_data = pd.DataFrame(
                [[
                    fever_enc,
                    cough_enc,
                    fatigue_enc,
                    breathing_enc,
                    age,
                    gender_enc,
                    bp,
                    cholesterol
                ]],
                columns=[
                    "fever",
                    "cough",
                    "fatigue",
                    "difficulty_breathing",
                    "age",
                    "gender",
                    "blood_pressure",
                    "cholesterol_level"
                ]
            )

        prediction = model.predict(input_data)[0]
        disease = encoders["disease"].inverse_transform([prediction])[0]

# ==========================
# RISK PREDICTION
# ==========================

        risk_input = pd.DataFrame([[age,bp,cholesterol]],columns=["age","blood_pressure","cholesterol_level"])
        risk_pred = risk_model.predict(risk_input)[0]
        risk_level = risk_pred
        # risk_level = encoders["risk_level"].inverse_transform([risk_pred])[0]
        save_prediction(disease,risk_level,age,gender)

# ==========================
# OUTPUT
# ==========================

        st.markdown(f"""
                <div style="
                padding:20px;
                background:#dcfce7;
                border-radius:15px;
                margin-top:10px;
                box-shadow:0 4px 12px rgba(0,0,0,0.1);
                ">
                <h3 style="
                color:#2563eb;
                margin-bottom:10px;
                font-weight:700;
                ">
                🩺 Predicted Disease
                </h3>

                <h2 style="
                color:#111827;
                font-weight:800;
                margin:0;
                ">
                {disease}
                </h2>
                </div>
                """, unsafe_allow_html=True)
        
        

        if risk_level == "High":
            color = "#dc2626"
            # st.error(f"🚨 Risk Level: {risk_level}")

        elif risk_level == "Medium":
            color = "#f59e0b"
            # st.warning(f"⚠️ Risk Level: {risk_level}")

        else:
            color = "#16a34a"
            # st.success(f"✅ Risk Level: {risk_level}")

        st.markdown(f"""
                    <div style="
                    padding:20px;
                    background:white;
                    border-left:8px solid {color};
                    border-radius:15px;
                    margin-top:10px;
                    box-shadow:0 4px 12px rgba(0,0,0,0.08);
                    ">
                    <h3 style="
                    color:{color};
                    font-weight:700;
                    margin-bottom:10px;
                    ">
                    ⚠️ Risk Level
                    </h3>

                    <h2 style="
                    color:#111827;
                    font-weight:800;
                    margin:0;
                    ">
                    {risk_level}
                    </h2>
                    </div>
                    """, unsafe_allow_html=True)

        recommendations = []

        if disease == "Diabetes":
            recommendations.extend([
                "Avoid Sugar",
                "Walk Daily",
                "Monitor Blood Sugar"
            ])

        elif disease == "Hypertension":

            recommendations.extend([
                "Reduce Salt Intake",
                "Exercise Daily",
                "Monitor Blood Pressure"
            ])

        elif disease == "Asthma":

            recommendations.extend([
                "Avoid Dust",
                "Use Inhaler",
                "Stay Hydrated"
            ])

        if risk_level == "High":

            recommendations.append(
                "Consult Doctor Immediately"
            )

        # PDF Creation
        pdf_file = create_pdf(
            patient_name,
            age,
            gender,
            disease,
            risk_level,
            recommendations=recommendations
        )

        with open(pdf_file, "rb") as pdf:
            st.download_button(
            label="📄 Download Health Report",
            data=pdf,
            file_name="Health_Report.pdf",
            mime="application/pdf"
        )
# ==========================
# RECOMMENDATIONS
# ==========================

       
        st.markdown("""
                    <h1 style="
                    color:#2563EB;
                    font-weight:800;
                    margin-top:30px;
                    margin-bottom:20px;
                    ">
                    💡 Personalized Recommendations
                    </h1>
                    """, unsafe_allow_html=True)

        for rec in recommendations :
            st.markdown(f"""
                    <div style="
                    background:linear-gradient(135deg,#eff6ff,#ffffff);
                    border:1px solid #dbeafe;
                    padding:18px;
                    border-radius:15px;
                    margin-bottom:12px;
                    ">
                        <span style="
                        color:#1e293b;
                        font-size:18px;
                        font-weight:700;
                        ">
                        ✔️ {rec}
                        </span>
                    </div>
                    """, unsafe_allow_html=True)

# ==========================
# ANALYTICS
# ==========================

elif page == "Analytics":

    st.markdown("""
            <style>

            [data-testid="stMetricValue"] {
                color: #FF4B4B !important;   /* Red */
                font-size: 40px !important;
                font-weight: bold !important;
            }

            [data-testid="stMetricLabel"] {
                color: #1E3A8A !important;   /* Blue */
                font-size: 18px !important;
                font-weight: bold !important;
            }

            </style>
            """, unsafe_allow_html=True)
    
    high_risk = len(
    df[df["risk_level"]=="High"]
    )

    medium_risk = len(
    df[df["risk_level"]=="Medium"]
    )

    low_risk = len(
    df[df["risk_level"]=="Low"]
    )

    col1,col2,col3 = st.columns(3)

    col1.metric(
    "High Risk",
    high_risk
    )

    col2.metric(
    "Medium Risk",
    medium_risk
    )

    col3.metric(
    "Low Risk",
    low_risk
    )


    st.markdown("""
            <h2 style='color:#2563eb'>
            📊 Healthcare Analytics Dashboard
            </h2>""", unsafe_allow_html=True)

    fig = px.histogram(
        df,
        x="age",
        nbins=20,
        title="Age Distribution"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

    fig2 = px.box(
        df,
        x="disease",
        y="age",
        title="Disease vs Age"
    )

    st.plotly_chart(
        fig2,
        use_container_width=True
    )

    fig3 = px.scatter(
        df,
        x="blood_pressure",
        y="cholesterol_level",
        color="disease",
        title="BP vs Cholesterol"
    )

    st.plotly_chart(
        fig3,
        use_container_width=True
    )

    st.markdown("""
            <h2 style='color:#2563eb'>
            ⚠️ Risk Level Distribution
            </h2>""", unsafe_allow_html=True)
    fig = px.pie(df,names="risk_level",title="Risk Level Breakdown")
    st.plotly_chart(fig, use_container_width=True)

    st.markdown("""
            <h2 style='color:#2563eb'>
            🏥 Disease Distribution
            </h2>""", unsafe_allow_html=True)
    disease_count = df["disease"].value_counts().reset_index()
    disease_count.columns = ["Disease", "Count"]
    fig = px.bar(disease_count,x="Disease",y="Count",color="Count",color_continuous_scale="Turbo",title="Disease Distribution")
    st.plotly_chart(fig, use_container_width=True)

    st.markdown("""
            <h2 style='color:#2563eb'>
            👨‍⚕️ Gender Distribution
            </h2>""", unsafe_allow_html=True)
    fig = px.pie(df,names="gender",title="Male vs Female")
    st.plotly_chart(fig, use_container_width=True)

    st.markdown("""
            <h2 style='color:#2563eb'>
            📈 Age Distribution
            </h2>""", unsafe_allow_html=True)
    fig = px.histogram(df,x="age",nbins=20,title="Patient Age Distribution")
    st.plotly_chart(fig, use_container_width=True)

    st.markdown("""
            <h2 style='color:#2563eb'>
            ❤️ Blood Pressure Distribution
            </h2>""", unsafe_allow_html=True)
    fig = px.histogram(df,x="blood_pressure",nbins=25,title="Blood Pressure Analysis")
    st.plotly_chart(fig, use_container_width=True)

    st.markdown("""
            <h2 style='color:#2563eb'>
            🩸 Cholesterol Distribution
            </h2>""", unsafe_allow_html=True)
    fig = px.histogram(df,x="cholesterol_level",nbins=25,title="Cholesterol Analysis")
    st.plotly_chart(fig, use_container_width=True)

# ==========================
# RECOMMENDATION PAGE
# ==========================

elif page == "Recommendations":

    st.markdown("""
            <h2 style='color:#2563eb'>
            💊 Health Recommendations
            </h2>""", unsafe_allow_html=True)

    disease = st.selectbox(
        "Select Disease",
        sorted(df["disease"].unique())
    )

    if disease == "Diabetes":

        st.info("""
        ✔ Avoid Sugar

        ✔ Daily Walking

        ✔ Drink Water

        ✔ Monitor Glucose
        """)

    elif disease == "Hypertension":

        st.info("""
        ✔ Reduce Salt

        ✔ Exercise Daily

        ✔ Avoid Stress

        ✔ Regular BP Check
        """)

    elif disease == "Asthma":

        st.info("""
        ✔ Avoid Dust

        ✔ Use Inhaler

        ✔ Breathing Exercise

        ✔ Stay Hydrated
        """)

    else:

        st.info(
            "Consult healthcare professional."
        )


# =========================
# Prediction History
# =========================

elif page == "Prediction History":
    st.markdown("""
            <h2 style='color:#2563eb'>
            📋 Prediction History
            </h2>
            """, unsafe_allow_html=True)
    file_path = "data/prediction_history.csv"

    if not os.path.exists(file_path):
        st.warning("No prediction history found.")
    elif os.path.getsize(file_path) == 0:
        st.warning("Prediction history file is empty.")
    else:
        history = pd.read_csv(file_path)
        st.dataframe(
            history,
            use_container_width=True
        )


